/* =====================================================================
   Pacote de colecionáveis "geografia-v1" — 10 Nexóticos do Mundo de
   Geografia (catálogo aprovado: src/nexus/catalogo/catalogo_nexoticos.json).
   IDs e assets IMUTÁVEIS. Novos personagens entram em um NOVO pacote.
   Poderes: só conforto/aparência; nunca revelam respostas escolares.
   ===================================================================== */
GG.catalog.registerPack({
  packId: 'geografia-v1', version: '1.0.0', schemaVersion: 1, world: 'geografia', title: 'Nexóticos de Geografia',
  base: 'src/modules/geografia/nexoticos/',
  characters: [
    { id: 'geografia_mochilango', name: 'Mochilango', world: 'geografia', rarity: 'comum', order: 1,
      visual: 'Canguru laranja cuja bolsa é uma mochila de viagem cheia de mapas, cantil e bússola.',
      personality: 'Viajante prestativo; sempre tem espaço para mais uma lembrancinha.',
      idle: 'hop', celebrate: 'jump', sound: { wave: 'square', notes: [392, 494, 587], dur: 0.08 },
      unlock: [{ type: 'moduleStat', module: 'geografia', stat: 'questionsDone', min: 1, label: 'Conclua 1 questão em Geografia' }, { type: 'shop', price: 40 }, { type: 'fragments' }, { type: 'capsule' }],
      power: { id: 'bolso_extra', name: 'Bolso Extra', type: 'bag_slot', params: { slots: 1 }, scope: 'nexus_exploration', description: 'Adiciona um espaço para coleta decorativa durante a exploração.' },
      asset: '11_mochilango.png', alt: 'Criatura viajante que parece uma mochila animada.' },
    { id: 'geografia_bussola_biscoito', name: 'Bússola Biscoito', world: 'geografia', rarity: 'comum', order: 2,
      visual: 'Biscoito recheado redondo com uma bússola de verdade na tampa e tênis de corrida.',
      personality: 'Otimista e crocante; nunca se perde (mas às vezes se esfarela de rir).',
      idle: 'bob', celebrate: 'spin', sound: { wave: 'triangle', notes: [587, 523, 659], dur: 0.08 },
      unlock: [{ type: 'moduleStat', module: 'geografia', stat: 'questionsDone', min: 5, label: 'Conclua 5 questões em Geografia' }, { type: 'shop', price: 40 }, { type: 'fragments' }, { type: 'capsule' }],
      power: { id: 'norte_de_casa', name: 'Norte de Casa', type: 'compass_home', params: {}, scope: 'nexus_hub', description: 'Aponta para o destino já liberado mais próximo do hub.' },
      asset: '12_bussola_biscoito.png', alt: 'Biscoito redondo com ponteiro de bússola.' },
    { id: 'geografia_capimapa', name: 'Capimapa', world: 'geografia', rarity: 'raro', order: 3,
      visual: 'Capivara exploradora com a pelagem desenhada como um mapa colorido e um lenço de aventureira.',
      personality: 'Tranquila e sabida; conhece todos os atalhos (e os lugares mais fresquinhos para descansar).',
      idle: 'sway', celebrate: 'jump', sound: { wave: 'triangle', notes: [330, 440, 554], dur: 0.1 },
      unlock: [{ type: 'moduleStat', module: 'geografia', stat: 'missionsDone', min: 2, label: 'Conclua 2 fases em Geografia' }, { type: 'shop', price: 100 }, { type: 'fragments' }, { type: 'capsule' }],
      power: { id: 'rota_amiga', name: 'Rota Amiga', type: 'route_hint', params: {}, scope: 'nexus_hub', description: 'Destaca o menor caminho no hub, nunca respostas escolares.' },
      asset: '13_capimapa.png', alt: 'Capivara exploradora com corpo e acessórios de mapa.' },
    { id: 'geografia_tucano_transito', name: 'Tucano Trânsito', world: 'geografia', rarity: 'raro', order: 4,
      visual: 'Tucano com o bico listrado como faixa de pedestre e um semáforo no peito.',
      personality: 'Organizado e falante; adora avisar “sinal verde, pode ir!”.',
      idle: 'bob', celebrate: 'flip', sound: { wave: 'square', notes: [784, 659, 784, 988], dur: 0.06 },
      unlock: [{ type: 'moduleStat', module: 'geografia', stat: 'questionsDone', min: 15, label: 'Conclua 15 questões em Geografia' }, { type: 'shop', price: 100 }, { type: 'fragments' }, { type: 'capsule' }],
      power: { id: 'sinal_verde', name: 'Sinal Verde', type: 'round_delay', params: { seconds: 2 }, scope: 'nexus_arcade', description: 'Reduz a espera entre rodadas de arcade.' },
      asset: '14_tucano_transito.png', alt: 'Tucano colorido inspirado em placas e sinais de trânsito.' },
    { id: 'geografia_crocodilo_cartografo', name: 'Crocodilo Cartógrafo', world: 'geografia', rarity: 'epico', order: 5,
      visual: 'Crocodilo de chapéu de explorador, mapa enrolado nas mãos e cauda que termina em lápis.',
      personality: 'Caprichoso e paciente; marca cada lugar especial com um X caprichado.',
      idle: 'sway', celebrate: 'shake', sound: { wave: 'sawtooth', notes: [196, 262, 330, 392], dur: 0.09 },
      unlock: [{ type: 'moduleStat', module: 'geografia', stat: 'firstTry', min: 15, label: 'Acerte 15 questões de primeira em Geografia' }, { type: 'shop', price: 180 }, { type: 'fragments' }, { type: 'capsule' }],
      power: { id: 'marcador_de_mapa', name: 'Marcador de Mapa', type: 'map_marker', params: { markers: 1 }, scope: 'nexus_hub', description: 'Permite colocar um marcador pessoal no mapa do Nexus.' },
      asset: '15_crocodilo_cartografo.png', alt: 'Crocodilo aventureiro equipado com mapas.' },
    { id: 'geografia_montanha_patins', name: 'Montanha Patins', world: 'geografia', rarity: 'epico', order: 6,
      visual: 'Montanha de pico nevado com uma estrada em espiral e patins roxos brilhantes.',
      personality: 'Radical e sorridente; desce qualquer ladeira gritando “uhuuu!”.',
      idle: 'wobble', celebrate: 'spin', sound: { wave: 'square', notes: [262, 392, 523, 784], dur: 0.07 },
      unlock: [{ type: 'moduleStat', module: 'geografia', stat: 'missionsDone', min: 8, label: 'Conclua 8 fases em Geografia' }, { type: 'shop', price: 180 }, { type: 'fragments' }, { type: 'capsule' }],
      power: { id: 'descida_turbo', name: 'Descida Turbo', type: 'race_accel', params: { percent: 30 }, scope: 'nexus_replay', description: 'Melhora a aceleração em corridas recreativas.' },
      asset: '16_montanha_patins.png', alt: 'Montanha sorridente usando patins.' },
    { id: 'geografia_globo_gorilao', name: 'Globo Gorilão', world: 'geografia', rarity: 'mitico', order: 7,
      visual: 'Gorila enorme com musgo nos ombros e a barriga em forma de globo terrestre.',
      personality: 'Forte e gentil; carrega o mundo nas costas e ainda oferece um abraço.',
      idle: 'bob', celebrate: 'shake', sound: { wave: 'sawtooth', notes: [110, 147, 196, 262], dur: 0.12 },
      unlock: [{ type: 'moduleStat', module: 'geografia', stat: 'bossesDone', min: 2, label: 'Vença 2 chefes em Geografia' }, { type: 'shop', price: 300 }, { type: 'fragments' }],
      power: { id: 'forca_continental', name: 'Força Continental', type: 'move_big_decor', params: {}, scope: 'nexus_base', description: 'Permite mover grandes decorações na base.' },
      asset: '17_globo_gorilao.png', alt: 'Gorila poderoso com corpo inspirado no globo terrestre.' },
    { id: 'geografia_rio_robozao', name: 'Rio Robozão', world: 'geografia', rarity: 'mitico', order: 8,
      visual: 'Robô gigante azul feito de correntezas, com cachoeiras nos ombros e punhos de onda.',
      personality: 'Brincalhão e incansável; nunca para, sempre segue o fluxo.',
      idle: 'wobble', celebrate: 'dance', sound: { wave: 'sine', notes: [330, 392, 494, 659, 494], dur: 0.08 },
      unlock: [{ type: 'moduleStat', module: 'geografia', stat: 'missionsDone', min: 16, label: 'Conclua as 16 fases de Geografia' }, { type: 'shop', price: 300 }, { type: 'fragments' }],
      power: { id: 'fluxo_azul', name: 'Fluxo Azul', type: 'water_dash', params: { percent: 80 }, scope: 'nexus_exploration', description: 'Concede um dash em caminhos aquáticos do Nexus.' },
      asset: '18_rio_robozao.png', alt: 'Robô azul grande com formas de rios e correnteza.' },
    { id: 'geografia_atlas_alado', name: 'Atlas Alado', world: 'geografia', rarity: 'lendario', order: 9,
      visual: 'Livro-atlas dourado com grandes asas de penas e um globo brilhante nas mãos.',
      personality: 'Nobre e aventureiro; conhece o céu de todos os mundos.',
      idle: 'float', celebrate: 'sparkle', sound: { wave: 'triangle', notes: [523, 659, 784, 1047, 1319], dur: 0.09 },
      unlock: [{ type: 'moduleStat', module: 'geografia', stat: 'questionsDone', min: 45, label: 'Domine o Mundo de Geografia (45/45 questões)' }, { type: 'shop', price: 450 }],
      power: { id: 'voo_direto', name: 'Voo Direto', type: 'fast_travel', params: {}, scope: 'nexus_hub', description: 'Libera viagem rápida entre áreas já abertas.' },
      asset: '19_atlas_alado.png', alt: 'Livro-atlas mágico com grandes asas.' },
    { id: 'geografia_tempestade_totem', name: 'Tempestade Totem', world: 'geografia', rarity: 'lendario', order: 10,
      visual: 'Totem fofo de nuvens empilhadas com arco-íris, sol, relâmpagos e um pequeno globo no centro.',
      personality: 'Imprevisível e divertido; muda de humor (e de clima) a cada minuto.',
      idle: 'pulse', celebrate: 'sparkle', sound: { wave: 'sine', notes: [880, 659, 1047, 784, 1319], dur: 0.1 },
      unlock: [{ type: 'collection', world: 'geografia', count: 8, label: 'Tenha 8 Nexóticos de Geografia' }, { type: 'shop', price: 450 }],
      power: { id: 'clima_maluco', name: 'Clima Maluco', type: 'weather', params: { modes: ['sol', 'chuva', 'neve', 'aurora', 'arco-iris'] }, scope: 'nexus_cosmetic', description: 'Troca clima e paleta cosmética do hub.' },
      asset: '20_tempestade_totem.png', alt: 'Totem fantástico cercado por nuvens, vento e relâmpagos.' }
  ]
}, GG.ROOT || '');
