/* =====================================================================
   Pacote de colecionáveis "ciencias-v1" — 10 Nexóticos do Mundo de
   Ciências (catálogo aprovado: src/nexus/catalogo/catalogo_nexoticos.json).
   IDs e assets IMUTÁVEIS. Novos personagens de Ciências entram em um
   NOVO pacote (ex.: ciencias-v2), nunca editando este.
   Poderes: só conforto/aparência no Nexus e nos replays recreativos.
   Nenhum poder revela, sugere ou corrige respostas escolares.
   ===================================================================== */
GG.catalog.registerPack({
  packId: 'ciencias-v1', version: '1.0.0', schemaVersion: 1, world: 'ciencias', title: 'Nexóticos de Ciências',
  base: 'src/modules/ciencias-legacy-adapter/nexoticos/',
  characters: [
    { id: 'ciencias_microbio_miojo', name: 'Micróbio Miojo', world: 'ciencias', rarity: 'comum', order: 1,
      visual: 'Micróbio verde-água com óculos de laboratório e uma cabeleira de macarrão instantâneo que balança quando ele corre.',
      personality: 'Apressado e animado; fala rápido e sempre acha que “já está pronto em 3 minutos”.',
      idle: 'wobble', celebrate: 'spin', sound: { wave: 'square', notes: [660, 880, 990], dur: 0.07 },
      unlock: [{ type: 'moduleStat', module: 'ciencias', stat: 'questionsDone', min: 1, label: 'Conclua 1 questão em Ciências' }, { type: 'shop', price: 40 }, { type: 'fragments' }, { type: 'capsule' }],
      power: { id: 'combo_elastico', name: 'Combo Elástico', type: 'combo_window', params: { seconds: 2 }, scope: 'nexus_replay', description: 'Amplia em 2 segundos a tolerância do combo em replays recreativos.' },
      asset: '01_microbio_miojo.png', alt: 'Criatura microscópica engraçada misturada com macarrão instantâneo.' },
    { id: 'ciencias_capivara_tubinho', name: 'Capivara Tubinho', world: 'ciencias', rarity: 'comum', order: 2,
      visual: 'Capivara cientista de óculos de proteção, carregando tubos de ensaio borbulhantes nas costas.',
      personality: 'Calma e protetora; nada a apressa e ela sempre oferece uma bolha para quem precisa.',
      idle: 'bob', celebrate: 'jump', sound: { wave: 'triangle', notes: [330, 392, 523], dur: 0.1 },
      unlock: [{ type: 'moduleStat', module: 'ciencias', stat: 'questionsDone', min: 5, label: 'Conclua 5 questões em Ciências' }, { type: 'shop', price: 40 }, { type: 'fragments' }, { type: 'capsule' }],
      power: { id: 'bolha_protetora', name: 'Bolha Protetora', type: 'shield', params: { hits: 1 }, scope: 'nexus_replay', description: 'Absorve um obstáculo inofensivo por rodada recreativa.' },
      asset: '02_capivara_tubinho.png', alt: 'Capivara cientista com tubos de laboratório.' },
    { id: 'ciencias_queijossauro', name: 'Queijossauro', world: 'ciencias', rarity: 'raro', order: 3,
      visual: 'Dinossauro amarelo com furinhos de queijo, jaleco e uma lupa gigante na cauda.',
      personality: 'Curioso e detalhista; examina tudo com a lupa e comemora cada descoberta.',
      idle: 'sway', celebrate: 'jump', sound: { wave: 'square', notes: [262, 330, 392, 523], dur: 0.08 },
      unlock: [{ type: 'moduleStat', module: 'ciencias', stat: 'missionsDone', min: 1, label: 'Restaure 1 cristal em Ciências' }, { type: 'shop', price: 100 }, { type: 'fragments' }, { type: 'capsule' }],
      power: { id: 'lupa_curiosa', name: 'Lupa Curiosa', type: 'highlight_interactive', params: { seconds: 3 }, scope: 'nexus_exploration', description: 'Destaca brevemente um objeto interativo já disponível.' },
      asset: '03_queijossauro.png', alt: 'Dinossauro amarelo com aparência divertida de queijo.' },
    { id: 'ciencias_folhinha_foguete', name: 'Folhinha Foguete', world: 'ciencias', rarity: 'raro', order: 4,
      visual: 'Folha verde com capacete e propulsores que soltam nuvenzinhas de vapor.',
      personality: 'Corajosa e veloz; conta regressiva é sua música favorita.',
      idle: 'float', celebrate: 'flip', sound: { wave: 'sawtooth', notes: [440, 660, 880, 1320], dur: 0.06 },
      unlock: [{ type: 'moduleStat', module: 'ciencias', stat: 'questionsDone', min: 15, label: 'Conclua 15 questões em Ciências' }, { type: 'shop', price: 100 }, { type: 'fragments' }, { type: 'capsule' }],
      power: { id: 'ecoimpulso', name: 'Ecoimpulso', type: 'speed_boost', params: { percent: 15 }, scope: 'nexus_replay', description: 'Oferece pequeno impulso de velocidade em replays.' },
      asset: '04_folhinha_foguete.png', alt: 'Folha verde transformada em pequeno foguete.' },
    { id: 'ciencias_bacteria_batucada', name: 'Bactéria Batucada', world: 'ciencias', rarity: 'epico', order: 5,
      visual: 'Bactéria roxa com fones de ouvido e um tamborzinho; os flagelos viram baquetas.',
      personality: 'Festeira e rítmica; transforma qualquer barulho em batucada.',
      idle: 'pulse', celebrate: 'dance', sound: { wave: 'square', notes: [196, 196, 294, 196, 392], dur: 0.07 },
      unlock: [{ type: 'moduleStat', module: 'ciencias', stat: 'firstTry', min: 15, label: 'Acerte 15 questões de primeira em Ciências' }, { type: 'shop', price: 180 }, { type: 'fragments' }, { type: 'capsule' }],
      power: { id: 'ritmo_magnetico', name: 'Ritmo Magnético', type: 'magnet', params: { radius: 70 }, scope: 'nexus_arcade', description: 'Aumenta o raio de coleta de itens recreativos.' },
      asset: '05_bacteria_batucada.png', alt: 'Bactéria colorida que toca percussão.' },
    { id: 'ciencias_macaco_microscopio', name: 'Macaco Microscópio', world: 'ciencias', rarity: 'epico', order: 6,
      visual: 'Macaco inventor com olhos-lente e um microscópio encaixado na cabeça.',
      personality: 'Inventor distraído; enxerga os detalhes que ninguém vê (e esquece onde deixou a banana).',
      idle: 'hop', celebrate: 'shake', sound: { wave: 'triangle', notes: [523, 494, 523, 659], dur: 0.08 },
      unlock: [{ type: 'moduleStat', module: 'ciencias', stat: 'missionsDone', min: 3, label: 'Restaure 3 cristais em Ciências' }, { type: 'shop', price: 180 }, { type: 'fragments' }, { type: 'capsule' }],
      power: { id: 'superzoom', name: 'Superzoom', type: 'zoom', params: { factor: 2 }, scope: 'nexus_ui', description: 'Amplia elementos visuais durante exploração e inspeção.' },
      asset: '06_macaco_microscopio.png', alt: 'Macaco inventor combinado com um microscópio.' },
    { id: 'ciencias_onca_oxigenio', name: 'Onça Oxigênio', world: 'ciencias', rarity: 'mitico', order: 7,
      visual: 'Onça-pintada veloz com máscara de mergulho e redemoinhos azuis de oxigênio nas patas.',
      personality: 'Atleta confiante e generosa; respira fundo antes de cada grande salto.',
      idle: 'sway', celebrate: 'flip', sound: { wave: 'sawtooth', notes: [294, 440, 587, 880], dur: 0.09 },
      unlock: [{ type: 'moduleStat', module: 'ciencias', stat: 'bossesDone', min: 1, label: 'Vença a Arena da Restauração em Ciências' }, { type: 'shop', price: 300 }, { type: 'fragments' }],
      power: { id: 'salto_de_vento', name: 'Salto de Vento', type: 'extra_jump', params: { jumps: 1 }, scope: 'nexus_replay', description: 'Concede um salto extra em fases recreativas.' },
      asset: '07_onca_oxigenio.png', alt: 'Onça veloz cercada por efeitos azuis de oxigênio.' },
    { id: 'ciencias_vulcao_gelatina', name: 'Vulcão Gelatina', world: 'ciencias', rarity: 'mitico', order: 8,
      visual: 'Vulcão sorridente de gelatina vermelha que borbulha e espirra bolinhas coloridas.',
      personality: 'Explosivo de alegria; quica em vez de andar e ri de tudo.',
      idle: 'wobble', celebrate: 'jump', sound: { wave: 'sine', notes: [220, 440, 330, 660], dur: 0.1 },
      unlock: [{ type: 'moduleStat', module: 'ciencias', stat: 'missionsDone', min: 6, label: 'Restaure os 6 cristais em Ciências' }, { type: 'shop', price: 300 }, { type: 'fragments' }],
      power: { id: 'pulo_gelatinoso', name: 'Pulo Gelatinoso', type: 'bounce_boost', params: { percent: 35 }, scope: 'nexus_replay', description: 'Aumenta o impulso em superfícies elásticas.' },
      asset: '08_vulcao_gelatina.png', alt: 'Vulcão sorridente feito de gelatina colorida.' },
    { id: 'ciencias_dragao_dna', name: 'Dragão DNA', world: 'ciencias', rarity: 'lendario', order: 9,
      visual: 'Dragão cristalino com asas iridescentes e o corpo enrolado em dupla hélice colorida.',
      personality: 'Sábio e brincalhão; lembra de cada caminho que já percorreu.',
      idle: 'float', celebrate: 'sparkle', sound: { wave: 'triangle', notes: [392, 523, 659, 784, 1047], dur: 0.09 },
      unlock: [{ type: 'moduleStat', module: 'ciencias', stat: 'questionsDone', min: 43, label: 'Domine o Mundo de Ciências (43/43 questões)' }, { type: 'shop', price: 450 }],
      power: { id: 'rastro_de_memoria', name: 'Rastro de Memória', type: 'ghost_run', params: {}, scope: 'nexus_replay', description: 'Mostra o fantasma cosmético da melhor rota anterior, nunca a resposta.' },
      asset: '09_dragao_dna.png', alt: 'Dragão fantástico com detalhes em dupla hélice de DNA.' },
    { id: 'ciencias_astro_axolote', name: 'Astro Axolote', world: 'ciencias', rarity: 'lendario', order: 10,
      visual: 'Axolote rosa de traje espacial, com brânquias de estrelas e planetas em órbita.',
      personality: 'Sonhador e tranquilo; faz o tempo parecer mais devagar quando sorri.',
      idle: 'float', celebrate: 'sparkle', sound: { wave: 'sine', notes: [523, 784, 1047, 1568], dur: 0.12 },
      unlock: [{ type: 'collection', world: 'ciencias', count: 8, label: 'Tenha 8 Nexóticos de Ciências' }, { type: 'shop', price: 450 }],
      power: { id: 'gravidade_leve', name: 'Gravidade Leve', type: 'slow_obstacles', params: { percent: 40, seconds: 3 }, scope: 'nexus_arcade', description: 'Desacelera brevemente obstáculos de arcade.' },
      asset: '10_astro_axolote.png', alt: 'Axolote astronauta com brilho cósmico.' }
  ]
}, GG.ROOT || '');
